site_name: 我的文档

# 指定使用Material主题
theme:
  name: 'material'
  # 自定义配色方案
  palette:
    primary: 'brown' # 设置主色调为棕色
    accent: 'brown'  # 设置强调色也为棕色（可选）

extra_javascript:
  - javascripts/extra.js



nav:
  - 首页: index.md
  - 站点介绍: intro.md
  
plugins:
  - search # 默认包含的搜索插件

